import type { Locale } from '@/i18n/config';

/**
 * Footer-only SEO label translations for locales whose full SEO landing
 * catalog (seo/<locale>.ts) isn't complete yet. The footer link grid uses
 * these so it's never left in Spanish. A complete catalog label always wins
 * over this supplement (see getSeoFooterLabel in seo-i18n.ts).
 */
export const SEO_FOOTER_LABELS: Partial<Record<Locale, Record<string, string>>> = {
  'pl': {
    'chat-online': 'Czat online',
    'chat-propinas': 'Czat z napiwkami',
    'chat-movil': 'Czat mobilny',
    'chatroulette': 'ChatRoulette',
    'chat-amigos': 'Czat ze znajomymi',
    'chat-privado': 'Czat prywatny',
    'chat-token': 'Czat token',
    'chat-tips': 'Czat tips',
    'chatear-online': 'Czatować online',
    'chat-en-espanol': 'Czat po hiszpańsku',
    'chat-espana': 'Czat Hiszpania',
    'chat-hablahispana': 'Czat hiszpańskojęzyczny',
    'chat-gratis': 'Czat za darmo',
    'ganar-dinero-chat': 'Zarabiaj na czacie',
    'gana-dinero-chateando': 'Zarabiaj, czatując',
    'chat-espanol-gratis': 'Darmowy czat po hiszpańsku',
    'chat-espanol-free': 'Czat po hiszpańsku free',
    'chat-espanol-sin-registro': 'Czat po hiszpańsku bez rejestracji',
    'chat-argentina': 'Czat Argentyna',
    'chat-brasil': 'Czat Brazylia',
    'chat-bogota': 'Czat Bogota',
    'chat-bolivia': 'Czat Boliwia',
    'chat-buenos-aires': 'Czat Buenos Aires',
    'chat-chile': 'Czat Chile',
    'chat-colombia': 'Czat Kolumbia',
    'chat-costa-rica': 'Czat Kostaryka',
    'chat-cuba': 'Czat Kuba',
    'chat-ecuador': 'Czat Ekwador',
    'chat-el-salvador': 'Czat Salwador',
    'chat-espana-pais': 'Czat Hiszpania (kraj)',
    'chat-guatemala': 'Czat Gwatemala',
    'chat-honduras': 'Czat Honduras',
    'chat-mexico': 'Czat Meksyk',
    'chat-nicaragua': 'Czat Nikaragua',
    'chat-republica-dominicana': 'Czat Dominikana',
    'chat-peru': 'Czat Peru',
    'chat-panama': 'Czat Panama',
    'chat-paraguay': 'Czat Paragwaj',
    'chat-puerto-rico': 'Czat Portoryko',
    'chat-tijuana': 'Czat Tijuana',
    'chat-uruguay': 'Czat Urugwaj',
    'chat-venezuela': 'Czat Wenezuela',
  },
  'nl': {
    'chat-online': 'Online chat',
    'chat-propinas': 'Chat met fooien',
    'chat-movil': 'Mobiele chat',
    'chatroulette': 'ChatRoulette',
    'chat-amigos': 'Chat met vrienden',
    'chat-privado': 'Privéchat',
    'chat-token': 'Chat-token',
    'chat-tips': 'Chat tips',
    'chatear-online': 'Online chatten',
    'chat-en-espanol': 'Chat in het Spaans',
    'chat-espana': 'Chat Spanje',
    'chat-hablahispana': 'Spaanstalige chat',
    'chat-gratis': 'Gratis chat',
    'ganar-dinero-chat': 'Geld verdienen met chatten',
    'gana-dinero-chateando': 'Verdien geld met chatten',
    'chat-espanol-gratis': 'Gratis Spaanse chat',
    'chat-espanol-free': 'Spaanse chat free',
    'chat-espanol-sin-registro': 'Spaanse chat zonder registratie',
    'chat-argentina': 'Chat Argentinië',
    'chat-brasil': 'Chat Brazilië',
    'chat-bogota': 'Chat Bogota',
    'chat-bolivia': 'Chat Bolivia',
    'chat-buenos-aires': 'Chat Buenos Aires',
    'chat-chile': 'Chat Chili',
    'chat-colombia': 'Chat Colombia',
    'chat-costa-rica': 'Chat Costa Rica',
    'chat-cuba': 'Chat Cuba',
    'chat-ecuador': 'Chat Ecuador',
    'chat-el-salvador': 'Chat El Salvador',
    'chat-espana-pais': 'Chat Spanje (land)',
    'chat-guatemala': 'Chat Guatemala',
    'chat-honduras': 'Chat Honduras',
    'chat-mexico': 'Chat Mexico',
    'chat-nicaragua': 'Chat Nicaragua',
    'chat-republica-dominicana': 'Chat Dominicaanse Republiek',
    'chat-peru': 'Chat Peru',
    'chat-panama': 'Chat Panama',
    'chat-paraguay': 'Chat Paraguay',
    'chat-puerto-rico': 'Chat Puerto Rico',
    'chat-tijuana': 'Chat Tijuana',
    'chat-uruguay': 'Chat Uruguay',
    'chat-venezuela': 'Chat Venezuela',
  },
  'tr': {
    'chat-online': 'Online sohbet',
    'chat-propinas': 'Bahşişli sohbet',
    'chat-movil': 'Mobil sohbet',
    'chatroulette': 'ChatRoulette',
    'chat-amigos': 'Arkadaşlarla sohbet',
    'chat-privado': 'Özel sohbet',
    'chat-token': 'Token sohbet',
    'chat-tips': 'Sohbet tips',
    'chatear-online': 'Online sohbet et',
    'chat-en-espanol': 'İspanyolca sohbet',
    'chat-espana': 'İspanya sohbet',
    'chat-hablahispana': 'İspanyolca konuşan sohbet',
    'chat-gratis': 'Ücretsiz sohbet',
    'ganar-dinero-chat': 'Sohbetle para kazan',
    'gana-dinero-chateando': 'Sohbet ederek para kazan',
    'chat-espanol-gratis': 'Ücretsiz İspanyolca sohbet',
    'chat-espanol-free': 'İspanyolca sohbet free',
    'chat-espanol-sin-registro': 'Kayıtsız İspanyolca sohbet',
    'chat-argentina': 'Arjantin sohbet',
    'chat-brasil': 'Brezilya sohbet',
    'chat-bogota': 'Bogota sohbet',
    'chat-bolivia': 'Bolivya sohbet',
    'chat-buenos-aires': 'Buenos Aires sohbet',
    'chat-chile': 'Şili sohbet',
    'chat-colombia': 'Kolombiya sohbet',
    'chat-costa-rica': 'Kosta Rika sohbet',
    'chat-cuba': 'Küba sohbet',
    'chat-ecuador': 'Ekvador sohbet',
    'chat-el-salvador': 'El Salvador sohbet',
    'chat-espana-pais': 'İspanya sohbet (ülke)',
    'chat-guatemala': 'Guatemala sohbet',
    'chat-honduras': 'Honduras sohbet',
    'chat-mexico': 'Meksika sohbet',
    'chat-nicaragua': 'Nikaragua sohbet',
    'chat-republica-dominicana': 'Dominik Cumhuriyeti sohbet',
    'chat-peru': 'Peru sohbet',
    'chat-panama': 'Panama sohbet',
    'chat-paraguay': 'Paraguay sohbet',
    'chat-puerto-rico': 'Porto Riko sohbet',
    'chat-tijuana': 'Tijuana sohbet',
    'chat-uruguay': 'Uruguay sohbet',
    'chat-venezuela': 'Venezuela sohbet',
  },
  'uk': {
    'chat-online': 'Онлайн-чат',
    'chat-propinas': 'Чат із чайовими',
    'chat-movil': 'Мобільний чат',
    'chatroulette': 'ChatRoulette',
    'chat-amigos': 'Чат із друзями',
    'chat-privado': 'Приватний чат',
    'chat-token': 'Чат токен',
    'chat-tips': 'Чат tips',
    'chatear-online': 'Спілкуватися онлайн',
    'chat-en-espanol': 'Чат іспанською',
    'chat-espana': 'Чат Іспанія',
    'chat-hablahispana': 'Іспаномовний чат',
    'chat-gratis': 'Безкоштовний чат',
    'ganar-dinero-chat': 'Заробляти в чаті',
    'gana-dinero-chateando': 'Заробляй, спілкуючись',
    'chat-espanol-gratis': 'Безкоштовний чат іспанською',
    'chat-espanol-free': 'Чат іспанською free',
    'chat-espanol-sin-registro': 'Чат іспанською без реєстрації',
    'chat-argentina': 'Чат Аргентина',
    'chat-brasil': 'Чат Бразилія',
    'chat-bogota': 'Чат Богота',
    'chat-bolivia': 'Чат Болівія',
    'chat-buenos-aires': 'Чат Буенос-Айрес',
    'chat-chile': 'Чат Чилі',
    'chat-colombia': 'Чат Колумбія',
    'chat-costa-rica': 'Чат Коста-Рика',
    'chat-cuba': 'Чат Куба',
    'chat-ecuador': 'Чат Еквадор',
    'chat-el-salvador': 'Чат Сальвадор',
    'chat-espana-pais': 'Чат Іспанія (країна)',
    'chat-guatemala': 'Чат Гватемала',
    'chat-honduras': 'Чат Гондурас',
    'chat-mexico': 'Чат Мексика',
    'chat-nicaragua': 'Чат Нікарагуа',
    'chat-republica-dominicana': 'Чат Домініканська Республіка',
    'chat-peru': 'Чат Перу',
    'chat-panama': 'Чат Панама',
    'chat-paraguay': 'Чат Парагвай',
    'chat-puerto-rico': 'Чат Пуерто-Рико',
    'chat-tijuana': 'Чат Тіхуана',
    'chat-uruguay': 'Чат Уругвай',
    'chat-venezuela': 'Чат Венесуела',
  },
  'ur': {
    'chat-online': 'آن لائن چیٹ',
    'chat-propinas': 'ٹپس والی چیٹ',
    'chat-movil': 'موبائل چیٹ',
    'chatroulette': 'ChatRoulette',
    'chat-amigos': 'دوستوں سے چیٹ',
    'chat-privado': 'نجی چیٹ',
    'chat-token': 'ٹوکن چیٹ',
    'chat-tips': 'چیٹ tips',
    'chatear-online': 'آن لائن چیٹ کریں',
    'chat-en-espanol': 'ہسپانوی میں چیٹ',
    'chat-espana': 'اسپین چیٹ',
    'chat-hablahispana': 'ہسپانوی بولنے والوں کی چیٹ',
    'chat-gratis': 'مفت چیٹ',
    'ganar-dinero-chat': 'چیٹ سے پیسے کمائیں',
    'gana-dinero-chateando': 'چیٹ کر کے پیسے کمائیں',
    'chat-espanol-gratis': 'مفت ہسپانوی چیٹ',
    'chat-espanol-free': 'ہسپانوی چیٹ free',
    'chat-espanol-sin-registro': 'رجسٹریشن کے بغیر ہسپانوی چیٹ',
    'chat-argentina': 'چیٹ ارجنٹینا',
    'chat-brasil': 'چیٹ برازیل',
    'chat-bogota': 'چیٹ بگوٹا',
    'chat-bolivia': 'چیٹ بولیویا',
    'chat-buenos-aires': 'چیٹ بیونس آئرس',
    'chat-chile': 'چیٹ چلی',
    'chat-colombia': 'چیٹ کولمبیا',
    'chat-costa-rica': 'چیٹ کوسٹا ریکا',
    'chat-cuba': 'چیٹ کیوبا',
    'chat-ecuador': 'چیٹ ایکواڈور',
    'chat-el-salvador': 'چیٹ ایل سلواڈور',
    'chat-espana-pais': 'چیٹ اسپین (ملک)',
    'chat-guatemala': 'چیٹ گوئٹے مالا',
    'chat-honduras': 'چیٹ ہونڈوراس',
    'chat-mexico': 'چیٹ میکسیکو',
    'chat-nicaragua': 'چیٹ نکاراگوا',
    'chat-republica-dominicana': 'چیٹ ڈومینیکن ری پبلک',
    'chat-peru': 'چیٹ پیرو',
    'chat-panama': 'چیٹ پاناما',
    'chat-paraguay': 'چیٹ پیراگوئے',
    'chat-puerto-rico': 'چیٹ پورٹو ریکو',
    'chat-tijuana': 'چیٹ تیہوانا',
    'chat-uruguay': 'چیٹ یوراگوئے',
    'chat-venezuela': 'چیٹ وینزویلا',
  },
  'pcm': {
    'chat-online': 'Online chat',
    'chat-propinas': 'Chat wit tips',
    'chat-movil': 'Mobile chat',
    'chatroulette': 'ChatRoulette',
    'chat-amigos': 'Chat wit friends',
    'chat-privado': 'Private chat',
    'chat-token': 'Token chat',
    'chat-tips': 'Chat tips',
    'chatear-online': 'Chat online',
    'chat-en-espanol': 'Spanish chat',
    'chat-espana': 'Spain chat',
    'chat-hablahispana': 'Spanish-speaking chat',
    'chat-gratis': 'Free chat',
    'ganar-dinero-chat': 'Make money for chat',
    'gana-dinero-chateando': 'Make money as you dey chat',
    'chat-espanol-gratis': 'Free Spanish chat',
    'chat-espanol-free': 'Spanish chat free',
    'chat-espanol-sin-registro': 'Spanish chat, no registration',
    'chat-argentina': 'Chat Argentina',
    'chat-brasil': 'Chat Brazil',
    'chat-bogota': 'Chat Bogota',
    'chat-bolivia': 'Chat Bolivia',
    'chat-buenos-aires': 'Chat Buenos Aires',
    'chat-chile': 'Chat Chile',
    'chat-colombia': 'Chat Colombia',
    'chat-costa-rica': 'Chat Costa Rica',
    'chat-cuba': 'Chat Cuba',
    'chat-ecuador': 'Chat Ecuador',
    'chat-el-salvador': 'Chat El Salvador',
    'chat-espana-pais': 'Chat Spain (country)',
    'chat-guatemala': 'Chat Guatemala',
    'chat-honduras': 'Chat Honduras',
    'chat-mexico': 'Chat Mexico',
    'chat-nicaragua': 'Chat Nicaragua',
    'chat-republica-dominicana': 'Chat Dominican Republic',
    'chat-peru': 'Chat Peru',
    'chat-panama': 'Chat Panama',
    'chat-paraguay': 'Chat Paraguay',
    'chat-puerto-rico': 'Chat Puerto Rico',
    'chat-tijuana': 'Chat Tijuana',
    'chat-uruguay': 'Chat Uruguay',
    'chat-venezuela': 'Chat Venezuela',
  },
};
