// AUTO-GENERATED region/subdivision data per country. Powers the country
// landing 'por provincias/estados/...' link section and a /c/<slug> landing
// for each subdivision (generated in seo-pages.ts). Spain reuses the existing
// province slugs; other countries use a -<pais> suffix to keep slugs unique.
export interface RegionLink {
  name: string;
  slug: string;
}
export interface CountryRegions {
  countryDisplay: string;
  noun: string;
  nounPlural: string;
  regions: RegionLink[];
}

export const COUNTRY_REGIONS: Record<string, CountryRegions> = {
  "chat-argentina": {
    countryDisplay: "Argentina",
    noun: "provincia",
    nounPlural: "provincias",
    regions: [
      { name: "Buenos Aires", slug: "chat-buenos-aires-argentina" },
      { name: "Ciudad de Buenos Aires", slug: "chat-ciudad-de-buenos-aires-argentina" },
      { name: "Catamarca", slug: "chat-catamarca-argentina" },
      { name: "Chaco", slug: "chat-chaco-argentina" },
      { name: "Chubut", slug: "chat-chubut-argentina" },
      { name: "Córdoba", slug: "chat-cordoba-argentina" },
      { name: "Corrientes", slug: "chat-corrientes-argentina" },
      { name: "Entre Ríos", slug: "chat-entre-rios-argentina" },
      { name: "Formosa", slug: "chat-formosa-argentina" },
      { name: "Jujuy", slug: "chat-jujuy-argentina" },
      { name: "La Pampa", slug: "chat-la-pampa-argentina" },
      { name: "La Rioja", slug: "chat-la-rioja-argentina" },
      { name: "Mendoza", slug: "chat-mendoza-argentina" },
      { name: "Misiones", slug: "chat-misiones-argentina" },
      { name: "Neuquén", slug: "chat-neuquen-argentina" },
      { name: "Río Negro", slug: "chat-rio-negro-argentina" },
      { name: "Salta", slug: "chat-salta-argentina" },
      { name: "San Juan", slug: "chat-san-juan-argentina" },
      { name: "San Luis", slug: "chat-san-luis-argentina" },
      { name: "Santa Cruz", slug: "chat-santa-cruz-argentina" },
      { name: "Santa Fe", slug: "chat-santa-fe-argentina" },
      { name: "Santiago del Estero", slug: "chat-santiago-del-estero-argentina" },
      { name: "Tierra del Fuego", slug: "chat-tierra-del-fuego-argentina" },
      { name: "Tucumán", slug: "chat-tucuman-argentina" },
    ],
  },
  "chat-brasil": {
    countryDisplay: "Brasil",
    noun: "estado",
    nounPlural: "estados",
    regions: [
      { name: "Acre", slug: "chat-acre-brasil" },
      { name: "Alagoas", slug: "chat-alagoas-brasil" },
      { name: "Amapá", slug: "chat-amapa-brasil" },
      { name: "Amazonas", slug: "chat-amazonas-brasil" },
      { name: "Bahía", slug: "chat-bahia-brasil" },
      { name: "Ceará", slug: "chat-ceara-brasil" },
      { name: "Distrito Federal", slug: "chat-distrito-federal-brasil" },
      { name: "Espírito Santo", slug: "chat-espirito-santo-brasil" },
      { name: "Goiás", slug: "chat-goias-brasil" },
      { name: "Maranhão", slug: "chat-maranhao-brasil" },
      { name: "Mato Grosso", slug: "chat-mato-grosso-brasil" },
      { name: "Mato Grosso do Sul", slug: "chat-mato-grosso-do-sul-brasil" },
      { name: "Minas Gerais", slug: "chat-minas-gerais-brasil" },
      { name: "Pará", slug: "chat-para-brasil" },
      { name: "Paraíba", slug: "chat-paraiba-brasil" },
      { name: "Paraná", slug: "chat-parana-brasil" },
      { name: "Pernambuco", slug: "chat-pernambuco-brasil" },
      { name: "Piauí", slug: "chat-piaui-brasil" },
      { name: "Río de Janeiro", slug: "chat-rio-de-janeiro-brasil" },
      { name: "Rio Grande do Norte", slug: "chat-rio-grande-do-norte-brasil" },
      { name: "Rio Grande do Sul", slug: "chat-rio-grande-do-sul-brasil" },
      { name: "Rondônia", slug: "chat-rondonia-brasil" },
      { name: "Roraima", slug: "chat-roraima-brasil" },
      { name: "Santa Catarina", slug: "chat-santa-catarina-brasil" },
      { name: "São Paulo", slug: "chat-sao-paulo-brasil" },
      { name: "Sergipe", slug: "chat-sergipe-brasil" },
      { name: "Tocantins", slug: "chat-tocantins-brasil" },
    ],
  },
  "chat-bolivia": {
    countryDisplay: "Bolivia",
    noun: "departamento",
    nounPlural: "departamentos",
    regions: [
      { name: "Beni", slug: "chat-beni-bolivia" },
      { name: "Chuquisaca", slug: "chat-chuquisaca-bolivia" },
      { name: "Cochabamba", slug: "chat-cochabamba-bolivia" },
      { name: "La Paz", slug: "chat-la-paz-bolivia" },
      { name: "Oruro", slug: "chat-oruro-bolivia" },
      { name: "Pando", slug: "chat-pando-bolivia" },
      { name: "Potosí", slug: "chat-potosi-bolivia" },
      { name: "Santa Cruz", slug: "chat-santa-cruz-bolivia" },
      { name: "Tarija", slug: "chat-tarija-bolivia" },
    ],
  },
  "chat-chile": {
    countryDisplay: "Chile",
    noun: "región",
    nounPlural: "regiones",
    regions: [
      { name: "Arica y Parinacota", slug: "chat-arica-y-parinacota-chile" },
      { name: "Tarapacá", slug: "chat-tarapaca-chile" },
      { name: "Antofagasta", slug: "chat-antofagasta-chile" },
      { name: "Atacama", slug: "chat-atacama-chile" },
      { name: "Coquimbo", slug: "chat-coquimbo-chile" },
      { name: "Valparaíso", slug: "chat-valparaiso-chile" },
      { name: "Metropolitana de Santiago", slug: "chat-metropolitana-de-santiago-chile" },
      { name: "O’Higgins", slug: "chat-o-higgins-chile" },
      { name: "Maule", slug: "chat-maule-chile" },
      { name: "Ñuble", slug: "chat-nuble-chile" },
      { name: "Biobío", slug: "chat-biobio-chile" },
      { name: "La Araucanía", slug: "chat-la-araucania-chile" },
      { name: "Los Ríos", slug: "chat-los-rios-chile" },
      { name: "Los Lagos", slug: "chat-los-lagos-chile" },
      { name: "Aysén", slug: "chat-aysen-chile" },
      { name: "Magallanes", slug: "chat-magallanes-chile" },
    ],
  },
  "chat-colombia": {
    countryDisplay: "Colombia",
    noun: "departamento",
    nounPlural: "departamentos",
    regions: [
      { name: "Amazonas", slug: "chat-amazonas-colombia" },
      { name: "Antioquia", slug: "chat-antioquia-colombia" },
      { name: "Arauca", slug: "chat-arauca-colombia" },
      { name: "Atlántico", slug: "chat-atlantico-colombia" },
      { name: "Bolívar", slug: "chat-bolivar-colombia" },
      { name: "Boyacá", slug: "chat-boyaca-colombia" },
      { name: "Caldas", slug: "chat-caldas-colombia" },
      { name: "Caquetá", slug: "chat-caqueta-colombia" },
      { name: "Casanare", slug: "chat-casanare-colombia" },
      { name: "Cauca", slug: "chat-cauca-colombia" },
      { name: "Cesar", slug: "chat-cesar-colombia" },
      { name: "Chocó", slug: "chat-choco-colombia" },
      { name: "Córdoba", slug: "chat-cordoba-colombia" },
      { name: "Cundinamarca", slug: "chat-cundinamarca-colombia" },
      { name: "Guainía", slug: "chat-guainia-colombia" },
      { name: "Guaviare", slug: "chat-guaviare-colombia" },
      { name: "Huila", slug: "chat-huila-colombia" },
      { name: "La Guajira", slug: "chat-la-guajira-colombia" },
      { name: "Magdalena", slug: "chat-magdalena-colombia" },
      { name: "Meta", slug: "chat-meta-colombia" },
      { name: "Nariño", slug: "chat-narino-colombia" },
      { name: "Norte de Santander", slug: "chat-norte-de-santander-colombia" },
      { name: "Putumayo", slug: "chat-putumayo-colombia" },
      { name: "Quindío", slug: "chat-quindio-colombia" },
      { name: "Risaralda", slug: "chat-risaralda-colombia" },
      { name: "Santander", slug: "chat-santander-colombia" },
      { name: "Sucre", slug: "chat-sucre-colombia" },
      { name: "Tolima", slug: "chat-tolima-colombia" },
      { name: "Valle del Cauca", slug: "chat-valle-del-cauca-colombia" },
      { name: "Vaupés", slug: "chat-vaupes-colombia" },
      { name: "Vichada", slug: "chat-vichada-colombia" },
    ],
  },
  "chat-costa-rica": {
    countryDisplay: "Costa Rica",
    noun: "provincia",
    nounPlural: "provincias",
    regions: [
      { name: "San José", slug: "chat-san-jose-costa-rica" },
      { name: "Alajuela", slug: "chat-alajuela-costa-rica" },
      { name: "Cartago", slug: "chat-cartago-costa-rica" },
      { name: "Heredia", slug: "chat-heredia-costa-rica" },
      { name: "Guanacaste", slug: "chat-guanacaste-costa-rica" },
      { name: "Puntarenas", slug: "chat-puntarenas-costa-rica" },
      { name: "Limón", slug: "chat-limon-costa-rica" },
    ],
  },
  "chat-cuba": {
    countryDisplay: "Cuba",
    noun: "provincia",
    nounPlural: "provincias",
    regions: [
      { name: "Pinar del Río", slug: "chat-pinar-del-rio-cuba" },
      { name: "Artemisa", slug: "chat-artemisa-cuba" },
      { name: "La Habana", slug: "chat-la-habana-cuba" },
      { name: "Mayabeque", slug: "chat-mayabeque-cuba" },
      { name: "Matanzas", slug: "chat-matanzas-cuba" },
      { name: "Cienfuegos", slug: "chat-cienfuegos-cuba" },
      { name: "Villa Clara", slug: "chat-villa-clara-cuba" },
      { name: "Sancti Spíritus", slug: "chat-sancti-spiritus-cuba" },
      { name: "Ciego de Ávila", slug: "chat-ciego-de-avila-cuba" },
      { name: "Camagüey", slug: "chat-camaguey-cuba" },
      { name: "Las Tunas", slug: "chat-las-tunas-cuba" },
      { name: "Granma", slug: "chat-granma-cuba" },
      { name: "Holguín", slug: "chat-holguin-cuba" },
      { name: "Santiago de Cuba", slug: "chat-santiago-de-cuba-cuba" },
      { name: "Guantánamo", slug: "chat-guantanamo-cuba" },
    ],
  },
  "chat-ecuador": {
    countryDisplay: "Ecuador",
    noun: "provincia",
    nounPlural: "provincias",
    regions: [
      { name: "Azuay", slug: "chat-azuay-ecuador" },
      { name: "Bolívar", slug: "chat-bolivar-ecuador" },
      { name: "Cañar", slug: "chat-canar-ecuador" },
      { name: "Carchi", slug: "chat-carchi-ecuador" },
      { name: "Chimborazo", slug: "chat-chimborazo-ecuador" },
      { name: "Cotopaxi", slug: "chat-cotopaxi-ecuador" },
      { name: "El Oro", slug: "chat-el-oro-ecuador" },
      { name: "Esmeraldas", slug: "chat-esmeraldas-ecuador" },
      { name: "Galápagos", slug: "chat-galapagos-ecuador" },
      { name: "Guayas", slug: "chat-guayas-ecuador" },
      { name: "Imbabura", slug: "chat-imbabura-ecuador" },
      { name: "Loja", slug: "chat-loja-ecuador" },
      { name: "Los Ríos", slug: "chat-los-rios-ecuador" },
      { name: "Manabí", slug: "chat-manabi-ecuador" },
      { name: "Morona Santiago", slug: "chat-morona-santiago-ecuador" },
      { name: "Napo", slug: "chat-napo-ecuador" },
      { name: "Orellana", slug: "chat-orellana-ecuador" },
      { name: "Pastaza", slug: "chat-pastaza-ecuador" },
      { name: "Pichincha", slug: "chat-pichincha-ecuador" },
      { name: "Santa Elena", slug: "chat-santa-elena-ecuador" },
      { name: "Santo Domingo de los Tsáchilas", slug: "chat-santo-domingo-de-los-tsachilas-ecuador" },
      { name: "Sucumbíos", slug: "chat-sucumbios-ecuador" },
      { name: "Tungurahua", slug: "chat-tungurahua-ecuador" },
      { name: "Zamora Chinchipe", slug: "chat-zamora-chinchipe-ecuador" },
    ],
  },
  "chat-el-salvador": {
    countryDisplay: "El Salvador",
    noun: "departamento",
    nounPlural: "departamentos",
    regions: [
      { name: "Ahuachapán", slug: "chat-ahuachapan-el-salvador" },
      { name: "Cabañas", slug: "chat-cabanas-el-salvador" },
      { name: "Chalatenango", slug: "chat-chalatenango-el-salvador" },
      { name: "Cuscatlán", slug: "chat-cuscatlan-el-salvador" },
      { name: "La Libertad", slug: "chat-la-libertad-el-salvador" },
      { name: "La Paz", slug: "chat-la-paz-el-salvador" },
      { name: "La Unión", slug: "chat-la-union-el-salvador" },
      { name: "Morazán", slug: "chat-morazan-el-salvador" },
      { name: "San Miguel", slug: "chat-san-miguel-el-salvador" },
      { name: "San Salvador", slug: "chat-san-salvador-el-salvador" },
      { name: "San Vicente", slug: "chat-san-vicente-el-salvador" },
      { name: "Santa Ana", slug: "chat-santa-ana-el-salvador" },
      { name: "Sonsonate", slug: "chat-sonsonate-el-salvador" },
      { name: "Usulután", slug: "chat-usulutan-el-salvador" },
    ],
  },
  "chat-guatemala": {
    countryDisplay: "Guatemala",
    noun: "departamento",
    nounPlural: "departamentos",
    regions: [
      { name: "Alta Verapaz", slug: "chat-alta-verapaz-guatemala" },
      { name: "Baja Verapaz", slug: "chat-baja-verapaz-guatemala" },
      { name: "Chimaltenango", slug: "chat-chimaltenango-guatemala" },
      { name: "Chiquimula", slug: "chat-chiquimula-guatemala" },
      { name: "El Progreso", slug: "chat-el-progreso-guatemala" },
      { name: "Escuintla", slug: "chat-escuintla-guatemala" },
      { name: "Guatemala", slug: "chat-guatemala-guatemala" },
      { name: "Huehuetenango", slug: "chat-huehuetenango-guatemala" },
      { name: "Izabal", slug: "chat-izabal-guatemala" },
      { name: "Jalapa", slug: "chat-jalapa-guatemala" },
      { name: "Jutiapa", slug: "chat-jutiapa-guatemala" },
      { name: "Petén", slug: "chat-peten-guatemala" },
      { name: "Quetzaltenango", slug: "chat-quetzaltenango-guatemala" },
      { name: "Quiché", slug: "chat-quiche-guatemala" },
      { name: "Retalhuleu", slug: "chat-retalhuleu-guatemala" },
      { name: "Sacatepéquez", slug: "chat-sacatepequez-guatemala" },
      { name: "San Marcos", slug: "chat-san-marcos-guatemala" },
      { name: "Santa Rosa", slug: "chat-santa-rosa-guatemala" },
      { name: "Sololá", slug: "chat-solola-guatemala" },
      { name: "Suchitepéquez", slug: "chat-suchitepequez-guatemala" },
      { name: "Totonicapán", slug: "chat-totonicapan-guatemala" },
      { name: "Zacapa", slug: "chat-zacapa-guatemala" },
    ],
  },
  "chat-honduras": {
    countryDisplay: "Honduras",
    noun: "departamento",
    nounPlural: "departamentos",
    regions: [
      { name: "Atlántida", slug: "chat-atlantida-honduras" },
      { name: "Choluteca", slug: "chat-choluteca-honduras" },
      { name: "Colón", slug: "chat-colon-honduras" },
      { name: "Comayagua", slug: "chat-comayagua-honduras" },
      { name: "Copán", slug: "chat-copan-honduras" },
      { name: "Cortés", slug: "chat-cortes-honduras" },
      { name: "El Paraíso", slug: "chat-el-paraiso-honduras" },
      { name: "Francisco Morazán", slug: "chat-francisco-morazan-honduras" },
      { name: "Gracias a Dios", slug: "chat-gracias-a-dios-honduras" },
      { name: "Intibucá", slug: "chat-intibuca-honduras" },
      { name: "Islas de la Bahía", slug: "chat-islas-de-la-bahia-honduras" },
      { name: "La Paz", slug: "chat-la-paz-honduras" },
      { name: "Lempira", slug: "chat-lempira-honduras" },
      { name: "Ocotepeque", slug: "chat-ocotepeque-honduras" },
      { name: "Olancho", slug: "chat-olancho-honduras" },
      { name: "Santa Bárbara", slug: "chat-santa-barbara-honduras" },
      { name: "Valle", slug: "chat-valle-honduras" },
      { name: "Yoro", slug: "chat-yoro-honduras" },
    ],
  },
  "chat-mexico": {
    countryDisplay: "México",
    noun: "estado",
    nounPlural: "estados",
    regions: [
      { name: "Aguascalientes", slug: "chat-aguascalientes-mexico" },
      { name: "Baja California", slug: "chat-baja-california-mexico" },
      { name: "Baja California Sur", slug: "chat-baja-california-sur-mexico" },
      { name: "Campeche", slug: "chat-campeche-mexico" },
      { name: "Chiapas", slug: "chat-chiapas-mexico" },
      { name: "Chihuahua", slug: "chat-chihuahua-mexico" },
      { name: "Ciudad de México", slug: "chat-ciudad-de-mexico-mexico" },
      { name: "Coahuila", slug: "chat-coahuila-mexico" },
      { name: "Colima", slug: "chat-colima-mexico" },
      { name: "Durango", slug: "chat-durango-mexico" },
      { name: "Estado de México", slug: "chat-estado-de-mexico-mexico" },
      { name: "Guanajuato", slug: "chat-guanajuato-mexico" },
      { name: "Guerrero", slug: "chat-guerrero-mexico" },
      { name: "Hidalgo", slug: "chat-hidalgo-mexico" },
      { name: "Jalisco", slug: "chat-jalisco-mexico" },
      { name: "Michoacán", slug: "chat-michoacan-mexico" },
      { name: "Morelos", slug: "chat-morelos-mexico" },
      { name: "Nayarit", slug: "chat-nayarit-mexico" },
      { name: "Nuevo León", slug: "chat-nuevo-leon-mexico" },
      { name: "Oaxaca", slug: "chat-oaxaca-mexico" },
      { name: "Puebla", slug: "chat-puebla-mexico" },
      { name: "Querétaro", slug: "chat-queretaro-mexico" },
      { name: "Quintana Roo", slug: "chat-quintana-roo-mexico" },
      { name: "San Luis Potosí", slug: "chat-san-luis-potosi-mexico" },
      { name: "Sinaloa", slug: "chat-sinaloa-mexico" },
      { name: "Sonora", slug: "chat-sonora-mexico" },
      { name: "Tabasco", slug: "chat-tabasco-mexico" },
      { name: "Tamaulipas", slug: "chat-tamaulipas-mexico" },
      { name: "Tlaxcala", slug: "chat-tlaxcala-mexico" },
      { name: "Veracruz", slug: "chat-veracruz-mexico" },
      { name: "Yucatán", slug: "chat-yucatan-mexico" },
      { name: "Zacatecas", slug: "chat-zacatecas-mexico" },
    ],
  },
  "chat-nicaragua": {
    countryDisplay: "Nicaragua",
    noun: "departamento",
    nounPlural: "departamentos",
    regions: [
      { name: "Boaco", slug: "chat-boaco-nicaragua" },
      { name: "Carazo", slug: "chat-carazo-nicaragua" },
      { name: "Chinandega", slug: "chat-chinandega-nicaragua" },
      { name: "Chontales", slug: "chat-chontales-nicaragua" },
      { name: "Estelí", slug: "chat-esteli-nicaragua" },
      { name: "Granada", slug: "chat-granada-nicaragua" },
      { name: "Jinotega", slug: "chat-jinotega-nicaragua" },
      { name: "León", slug: "chat-leon-nicaragua" },
      { name: "Madriz", slug: "chat-madriz-nicaragua" },
      { name: "Managua", slug: "chat-managua-nicaragua" },
      { name: "Masaya", slug: "chat-masaya-nicaragua" },
      { name: "Matagalpa", slug: "chat-matagalpa-nicaragua" },
      { name: "Nueva Segovia", slug: "chat-nueva-segovia-nicaragua" },
      { name: "Río San Juan", slug: "chat-rio-san-juan-nicaragua" },
      { name: "Rivas", slug: "chat-rivas-nicaragua" },
    ],
  },
  "chat-republica-dominicana": {
    countryDisplay: "República Dominicana",
    noun: "provincia",
    nounPlural: "provincias",
    regions: [
      { name: "Azua", slug: "chat-azua-republica-dominicana" },
      { name: "Bahoruco", slug: "chat-bahoruco-republica-dominicana" },
      { name: "Barahona", slug: "chat-barahona-republica-dominicana" },
      { name: "Dajabón", slug: "chat-dajabon-republica-dominicana" },
      { name: "Distrito Nacional", slug: "chat-distrito-nacional-republica-dominicana" },
      { name: "Duarte", slug: "chat-duarte-republica-dominicana" },
      { name: "El Seibo", slug: "chat-el-seibo-republica-dominicana" },
      { name: "Elías Piña", slug: "chat-elias-pina-republica-dominicana" },
      { name: "Espaillat", slug: "chat-espaillat-republica-dominicana" },
      { name: "Hato Mayor", slug: "chat-hato-mayor-republica-dominicana" },
      { name: "Hermanas Mirabal", slug: "chat-hermanas-mirabal-republica-dominicana" },
      { name: "Independencia", slug: "chat-independencia-republica-dominicana" },
      { name: "La Altagracia", slug: "chat-la-altagracia-republica-dominicana" },
      { name: "La Romana", slug: "chat-la-romana-republica-dominicana" },
      { name: "La Vega", slug: "chat-la-vega-republica-dominicana" },
      { name: "María Trinidad Sánchez", slug: "chat-maria-trinidad-sanchez-republica-dominicana" },
      { name: "Monseñor Nouel", slug: "chat-monsenor-nouel-republica-dominicana" },
      { name: "Monte Cristi", slug: "chat-monte-cristi-republica-dominicana" },
      { name: "Monte Plata", slug: "chat-monte-plata-republica-dominicana" },
      { name: "Pedernales", slug: "chat-pedernales-republica-dominicana" },
      { name: "Peravia", slug: "chat-peravia-republica-dominicana" },
      { name: "Puerto Plata", slug: "chat-puerto-plata-republica-dominicana" },
      { name: "Samaná", slug: "chat-samana-republica-dominicana" },
      { name: "San Cristóbal", slug: "chat-san-cristobal-republica-dominicana" },
      { name: "San José de Ocoa", slug: "chat-san-jose-de-ocoa-republica-dominicana" },
      { name: "San Juan", slug: "chat-san-juan-republica-dominicana" },
      { name: "San Pedro de Macorís", slug: "chat-san-pedro-de-macoris-republica-dominicana" },
      { name: "Sánchez Ramírez", slug: "chat-sanchez-ramirez-republica-dominicana" },
      { name: "Santiago", slug: "chat-santiago-republica-dominicana" },
      { name: "Santiago Rodríguez", slug: "chat-santiago-rodriguez-republica-dominicana" },
      { name: "Santo Domingo", slug: "chat-santo-domingo-republica-dominicana" },
      { name: "Valverde", slug: "chat-valverde-republica-dominicana" },
    ],
  },
  "chat-peru": {
    countryDisplay: "Perú",
    noun: "departamento",
    nounPlural: "departamentos",
    regions: [
      { name: "Amazonas", slug: "chat-amazonas-peru" },
      { name: "Áncash", slug: "chat-ancash-peru" },
      { name: "Apurímac", slug: "chat-apurimac-peru" },
      { name: "Arequipa", slug: "chat-arequipa-peru" },
      { name: "Ayacucho", slug: "chat-ayacucho-peru" },
      { name: "Cajamarca", slug: "chat-cajamarca-peru" },
      { name: "Callao", slug: "chat-callao-peru" },
      { name: "Cusco", slug: "chat-cusco-peru" },
      { name: "Huancavelica", slug: "chat-huancavelica-peru" },
      { name: "Huánuco", slug: "chat-huanuco-peru" },
      { name: "Ica", slug: "chat-ica-peru" },
      { name: "Junín", slug: "chat-junin-peru" },
      { name: "La Libertad", slug: "chat-la-libertad-peru" },
      { name: "Lambayeque", slug: "chat-lambayeque-peru" },
      { name: "Lima", slug: "chat-lima-peru" },
      { name: "Loreto", slug: "chat-loreto-peru" },
      { name: "Madre de Dios", slug: "chat-madre-de-dios-peru" },
      { name: "Moquegua", slug: "chat-moquegua-peru" },
      { name: "Pasco", slug: "chat-pasco-peru" },
      { name: "Piura", slug: "chat-piura-peru" },
      { name: "Puno", slug: "chat-puno-peru" },
      { name: "San Martín", slug: "chat-san-martin-peru" },
      { name: "Tacna", slug: "chat-tacna-peru" },
      { name: "Tumbes", slug: "chat-tumbes-peru" },
      { name: "Ucayali", slug: "chat-ucayali-peru" },
    ],
  },
  "chat-panama": {
    countryDisplay: "Panamá",
    noun: "provincia",
    nounPlural: "provincias",
    regions: [
      { name: "Bocas del Toro", slug: "chat-bocas-del-toro-panama" },
      { name: "Coclé", slug: "chat-cocle-panama" },
      { name: "Colón", slug: "chat-colon-panama" },
      { name: "Chiriquí", slug: "chat-chiriqui-panama" },
      { name: "Darién", slug: "chat-darien-panama" },
      { name: "Herrera", slug: "chat-herrera-panama" },
      { name: "Los Santos", slug: "chat-los-santos-panama" },
      { name: "Panamá", slug: "chat-panama-panama" },
      { name: "Panamá Oeste", slug: "chat-panama-oeste-panama" },
      { name: "Veraguas", slug: "chat-veraguas-panama" },
    ],
  },
  "chat-paraguay": {
    countryDisplay: "Paraguay",
    noun: "departamento",
    nounPlural: "departamentos",
    regions: [
      { name: "Alto Paraguay", slug: "chat-alto-paraguay-paraguay" },
      { name: "Alto Paraná", slug: "chat-alto-parana-paraguay" },
      { name: "Amambay", slug: "chat-amambay-paraguay" },
      { name: "Asunción", slug: "chat-asuncion-paraguay" },
      { name: "Boquerón", slug: "chat-boqueron-paraguay" },
      { name: "Caaguazú", slug: "chat-caaguazu-paraguay" },
      { name: "Caazapá", slug: "chat-caazapa-paraguay" },
      { name: "Canindeyú", slug: "chat-canindeyu-paraguay" },
      { name: "Central", slug: "chat-central-paraguay" },
      { name: "Concepción", slug: "chat-concepcion-paraguay" },
      { name: "Cordillera", slug: "chat-cordillera-paraguay" },
      { name: "Guairá", slug: "chat-guaira-paraguay" },
      { name: "Itapúa", slug: "chat-itapua-paraguay" },
      { name: "Misiones", slug: "chat-misiones-paraguay" },
      { name: "Ñeembucú", slug: "chat-neembucu-paraguay" },
      { name: "Paraguarí", slug: "chat-paraguari-paraguay" },
      { name: "Presidente Hayes", slug: "chat-presidente-hayes-paraguay" },
      { name: "San Pedro", slug: "chat-san-pedro-paraguay" },
    ],
  },
  "chat-puerto-rico": {
    countryDisplay: "Puerto Rico",
    noun: "municipio",
    nounPlural: "municipios",
    regions: [
      { name: "San Juan", slug: "chat-san-juan-puerto-rico" },
      { name: "Bayamón", slug: "chat-bayamon-puerto-rico" },
      { name: "Carolina", slug: "chat-carolina-puerto-rico" },
      { name: "Ponce", slug: "chat-ponce-puerto-rico" },
      { name: "Caguas", slug: "chat-caguas-puerto-rico" },
      { name: "Guaynabo", slug: "chat-guaynabo-puerto-rico" },
      { name: "Mayagüez", slug: "chat-mayaguez-puerto-rico" },
      { name: "Arecibo", slug: "chat-arecibo-puerto-rico" },
      { name: "Aguadilla", slug: "chat-aguadilla-puerto-rico" },
      { name: "Fajardo", slug: "chat-fajardo-puerto-rico" },
      { name: "Humacao", slug: "chat-humacao-puerto-rico" },
      { name: "Vega Baja", slug: "chat-vega-baja-puerto-rico" },
    ],
  },
  "chat-uruguay": {
    countryDisplay: "Uruguay",
    noun: "departamento",
    nounPlural: "departamentos",
    regions: [
      { name: "Artigas", slug: "chat-artigas-uruguay" },
      { name: "Canelones", slug: "chat-canelones-uruguay" },
      { name: "Cerro Largo", slug: "chat-cerro-largo-uruguay" },
      { name: "Colonia", slug: "chat-colonia-uruguay" },
      { name: "Durazno", slug: "chat-durazno-uruguay" },
      { name: "Flores", slug: "chat-flores-uruguay" },
      { name: "Florida", slug: "chat-florida-uruguay" },
      { name: "Lavalleja", slug: "chat-lavalleja-uruguay" },
      { name: "Maldonado", slug: "chat-maldonado-uruguay" },
      { name: "Montevideo", slug: "chat-montevideo-uruguay" },
      { name: "Paysandú", slug: "chat-paysandu-uruguay" },
      { name: "Río Negro", slug: "chat-rio-negro-uruguay" },
      { name: "Rivera", slug: "chat-rivera-uruguay" },
      { name: "Rocha", slug: "chat-rocha-uruguay" },
      { name: "Salto", slug: "chat-salto-uruguay" },
      { name: "San José", slug: "chat-san-jose-uruguay" },
      { name: "Soriano", slug: "chat-soriano-uruguay" },
      { name: "Tacuarembó", slug: "chat-tacuarembo-uruguay" },
      { name: "Treinta y Tres", slug: "chat-treinta-y-tres-uruguay" },
    ],
  },
  "chat-venezuela": {
    countryDisplay: "Venezuela",
    noun: "estado",
    nounPlural: "estados",
    regions: [
      { name: "Amazonas", slug: "chat-amazonas-venezuela" },
      { name: "Anzoátegui", slug: "chat-anzoategui-venezuela" },
      { name: "Apure", slug: "chat-apure-venezuela" },
      { name: "Aragua", slug: "chat-aragua-venezuela" },
      { name: "Barinas", slug: "chat-barinas-venezuela" },
      { name: "Bolívar", slug: "chat-bolivar-venezuela" },
      { name: "Carabobo", slug: "chat-carabobo-venezuela" },
      { name: "Cojedes", slug: "chat-cojedes-venezuela" },
      { name: "Delta Amacuro", slug: "chat-delta-amacuro-venezuela" },
      { name: "Distrito Capital", slug: "chat-distrito-capital-venezuela" },
      { name: "Falcón", slug: "chat-falcon-venezuela" },
      { name: "Guárico", slug: "chat-guarico-venezuela" },
      { name: "Lara", slug: "chat-lara-venezuela" },
      { name: "Mérida", slug: "chat-merida-venezuela" },
      { name: "Miranda", slug: "chat-miranda-venezuela" },
      { name: "Monagas", slug: "chat-monagas-venezuela" },
      { name: "Nueva Esparta", slug: "chat-nueva-esparta-venezuela" },
      { name: "Portuguesa", slug: "chat-portuguesa-venezuela" },
      { name: "Sucre", slug: "chat-sucre-venezuela" },
      { name: "Táchira", slug: "chat-tachira-venezuela" },
      { name: "Trujillo", slug: "chat-trujillo-venezuela" },
      { name: "La Guaira", slug: "chat-la-guaira-venezuela" },
      { name: "Yaracuy", slug: "chat-yaracuy-venezuela" },
      { name: "Zulia", slug: "chat-zulia-venezuela" },
    ],
  },
  "chat-espana-pais": {
    countryDisplay: "España",
    noun: "provincia",
    nounPlural: "provincias",
    regions: [
      { name: "Álava", slug: "chat-alava" },
      { name: "Albacete", slug: "chat-albacete" },
      { name: "Alicante", slug: "chat-alicante" },
      { name: "Almería", slug: "chat-almeria" },
      { name: "Asturias", slug: "chat-asturias" },
      { name: "Ávila", slug: "chat-avila" },
      { name: "Badajoz", slug: "chat-badajoz" },
      { name: "Baleares", slug: "chat-baleares" },
      { name: "Barcelona", slug: "chat-barcelona" },
      { name: "Bizkaia", slug: "chat-bizkaia" },
      { name: "Burgos", slug: "chat-burgos" },
      { name: "Cáceres", slug: "chat-caceres" },
      { name: "Cádiz", slug: "chat-cadiz" },
      { name: "Cantabria", slug: "chat-cantabria" },
      { name: "Castellón", slug: "chat-castellon" },
      { name: "Ciudad Real", slug: "chat-ciudad-real" },
      { name: "Córdoba", slug: "chat-cordoba" },
      { name: "A Coruña", slug: "chat-a-coruna" },
      { name: "Cuenca", slug: "chat-cuenca" },
      { name: "Girona", slug: "chat-girona" },
      { name: "Granada", slug: "chat-granada" },
      { name: "Guadalajara", slug: "chat-guadalajara" },
      { name: "Gipuzkoa", slug: "chat-gipuzkoa" },
      { name: "Huelva", slug: "chat-huelva" },
      { name: "Huesca", slug: "chat-huesca" },
      { name: "Jaén", slug: "chat-jaen" },
      { name: "León", slug: "chat-leon" },
      { name: "Lleida", slug: "chat-lleida" },
      { name: "Lugo", slug: "chat-lugo" },
      { name: "Madrid", slug: "chat-madrid" },
      { name: "Málaga", slug: "chat-malaga" },
      { name: "Murcia", slug: "chat-murcia" },
      { name: "Navarra", slug: "chat-navarra" },
      { name: "Ourense", slug: "chat-ourense" },
      { name: "Palencia", slug: "chat-palencia" },
      { name: "Las Palmas", slug: "chat-las-palmas" },
      { name: "Pontevedra", slug: "chat-pontevedra" },
      { name: "La Rioja", slug: "chat-la-rioja" },
      { name: "Salamanca", slug: "chat-salamanca" },
      { name: "Santa Cruz de Tenerife", slug: "chat-tenerife" },
      { name: "Segovia", slug: "chat-segovia" },
      { name: "Sevilla", slug: "chat-sevilla" },
      { name: "Soria", slug: "chat-soria" },
      { name: "Tarragona", slug: "chat-tarragona" },
      { name: "Teruel", slug: "chat-teruel" },
      { name: "Toledo", slug: "chat-toledo" },
      { name: "Valencia", slug: "chat-valencia" },
      { name: "Valladolid", slug: "chat-valladolid" },
      { name: "Zamora", slug: "chat-zamora" },
      { name: "Zaragoza", slug: "chat-zaragoza" },
    ],
  },
};
